/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes_783931_10[] = { 0, 11, 22 };

// (before - mean) / scale
const float ei_classifier_anom_scale[3] = { 0.13682608119150486, 0.1355622234439798, 0.13774591348197132 };
const float ei_classifier_anom_mean[3] = { 0.20638361150927578, 0.2059110486102403, 0.2063664972982136 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[3] = {
	{ ( float[3] ) { 0.4664660096168518, 0.45513856410980225, 0.4672084450721741 }, 0.3232210202225032 },
	{ ( float[3] ) { 0.9200776219367981, 0.9289908409118652, 0.9217854738235474 }, 0.24014786203823166 },
	{ ( float[3] ) { -1.3864624500274658, -1.3849818706512451, -1.3866541385650635 }, 0.07787734747527389 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
